baseURL: https://ahmadmssm.github.io
languageCode: en-us
title: "Ahmad Mahmoud Saleh's Space"
theme: "toha"

markup:
  goldmark:
    renderer:
      unsafe: true
  
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/ahmadmssm/ahmadmssm.github.io
  gitBranch: main
  # specify whether you want to write some blog posts or not
  enableBlogPost: true
  # specify whether you want to show Table of Contents in reading page
  enableTOC: false
  darkMode:
    enable: true
    provider: darkreader
    default: system
  # Provide newsletter configuration.
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form
    enable: false
    # The inverted logo will be used in the initial transparent navbar and
    # the main logo will be used in the non-transparent navbar.
  # Background image of the landing page
  background: "images/site/background.jpg"
  features:
    analytics:
      enabled: true
      goatCounter:
        code: amssm
    comment:
      enable: true
      giscus:
      repo: ahmadmssm/ahmadmssm.github.io
      repoID: MDEwOlJlcG9zaXRvcnkzNzIxMDU2Njc=
      category: General
      categoryID: DIC_kwDOFi3hw84CPvD5
      # theme: light
      # map: url
      # reaction: 1
      # metadata: 0
      # inputPosition: bottom
      # crossOrigin: anonymous